lesson_2_hw
evgenii20/js pull request #2
Opened 2021-01-27 14:02 UTC by evgenii20

2021-01-27 14:20 UTC, Om1X requested changes

2021-01-27 14:20 UTC, Om1X commented on lesson_2/index3.html
> +            //console.log(`При а и b разных знаков\nсумма равна: ${a + b}`)
У Вас какая-то жесткая коллизия, везде в условиях допустимо значение 0, что совсем нелогично. Исправьте.

2021-01-27 14:31 UTC, evgenii20 commented
Исправил

2021-01-30 10:58 UTC, evgenii20 commented on lesson_2/index3.html
> +            //console.log(`При а и b разных знаков\nсумма равна: ${a + b}`)
Исправил.

2021-01-31 09:55 UTC, merged